---
- name: Provisioning ec2 instance
  hosts: localhost
  connection: local
  vars:
    instance_type: t2.micro
    key_name: fhlbckey
    image: ami-04be6a27b0206807f
    region: us-east-2
  tasks:
  - name: launching ec2
    ec2:
       instance_type: "{{ instance_type }}"
       key_name: "{{ key_name }}"
       image: "{{ image }}"
       region: "{{ region }}"
     # group: test
       count: 1
       instance_tags:
       vpc_subnet_id: subnet-ed86bf85
       assign_public_ip: yes
       wait: yes
       volumes:
         - device_name: /dev/xvda
           volume_type: gp2
           volume_size: 4
           delete_on_termination: yes
           tags:
             - {'Application':'Example'}
             - {'Drive':'C'}
             - {'Environment':'test'}
             - {'Name':'Instance'}
      register: ec2
  - name: create alarm
    ec2_meeteric_alarm:
      state: present
      statistic: maximium
      comparison: '>='
      threshold: 1.0
      period: 60
      evaluation_periods: 8
