---
- name: Provisioning ec2 instance
  hosts: localhost
  connection: local
  vars:
    Instance_name: fhcdbsumt02
    key_name: fhlbckey
    aws_region: us-east-2
    aws_instance_type: t2.micro
    aws_ami: ami-0cd3dfa4e37921605
    #aws_ami: ami-04be6a27b0206807f
    subnet: subnet-ed86bf85
    Business_Serv: BusService
    App_Name: TestApp
    Environment: DEV
    Owner_Name: JSMITH
    Patch_Group: Patch1
    aws_account_id: 935659307200
    instance_count: 1
    volume_size: 10
  #vars_file: 
    #- /vars/ec2_win_create_vars.yml
  tasks:
  - name: Launch ec2 Instance and attach a volume. Register the output.
    ec2:
      key_name: "{{ key_name }}"
      region: "{{ aws_region }}"
      #group: databases
      instance_type: "{{ aws_instance_type }}" 
      image: "{{ aws_ami }}"
      wait: yes
      #wait_timeout: 500
      count: "{{ instance_count }}"
      vpc_subnet_id: "{{ subnet }}"
      assign_public_ip: yes
      instance_tags:
         BusinessService: "{{ Business_Serv }}"
         Application: "{{ App_Name }}"
         Env: "{{ Environment }}"
         Name: "{{ Instance_name }}"
         Owner: "{{ Owner_Name }}"
         Patch Group: "{{ Patch_Group }}"
      volumes:
        - device_name: /dev/xvda
          volume_type: gp2
          volume_size: "{{ volume_size }}"
          delete_on_terminiation: true
    register: ec2result
   
  - debug:
      var=ec2result
   
  - debug:
      var=ec2result.instances[0].block_device_mapping["/dev/xvda"].volume_id
      
  - name: Add tags to Volume
    ec2_tag:
      region: "{{ aws_region }}"
      resource: "{{ ec2result.instances[0].block_device_mapping['/dev/xvda'].volume_id }}"
      state: present
      tags:
        Name: "{{ App_Name }}"
        Drive: root
        Env: "{{ Environment }}"
        Name: "{{ Instance_name }}"
  
  - name: Create an alarm for Status Check Failed Any and send email when triggered
    ec2_metric_alarm:
      state: present
      region: "{{ aws_region }}"
      name: "{{ Instance_name }}_NoAutorecover-statuscheck_instance-{{ ec2result.instance_ids }}"
      metric: "StatusCheckFailed"
      namespace: "AWS/EC2"
      statistic: Average
      comparison: ">="
      threshold: 1.0
      period: 60
      evaluation_periods: 8
      #unit: "Percent"
      description: "Status check alarm"
      dimensions: {'InstanceId' : '{{ ec2result.instance_ids }}'}
      alarm_actions: ['arn:aws:sns:us-east-2:935659307200:NotificationTopicEC2']
      
  #- name: Create alarm for Status Check Failed System and recover instance
    #ec2_metric_alarm:
      #state: present
      #region: "{{ aws_region }}"
      #name: "{{ Instance_name }}_Autorecover-statuscheck_instance-{{ ec2result.instance_ids }}"
      #metric: "StatusCheckFailed_System"
      #namespace: "AWS/EC2"
      #statistic: Average
      #comparison: ">="
      #threshold: 1
      #period: 60
      #evaluation_periods: 8
      #description: "Status Check Alarm - System"
      #dimensions: {'InstanceId' : '{{ ec2result.instance_ids }}'}
      #alarm_actions: ['arn:aws:automate:{{ aws_region }}:ec2:recover']
